cols_data_type = {
    "purchase_id": "string",
    "customer_id": "string",
    "first_name": "string",
    "last_name": "string",
    "country": "string",
    "club": "boolean",
    "card_type": "string",
    "gender": "string",
    "currency": "string",
    "email": "string",
    "product_id": "string",
    "product_name": "string",
    "product_price": "double",
    "quantity": "int",
    "department_id": "string",
    "department_name": "string",
    "sub_department_id": "string",
    "sub_department_name": "string",
    "purchase_time": "timestamp",
    "online": "boolean",
    "country_code": "string",
    "total": "double",
    "city": "string"
}